In [19]:
import numpy

In [115]:
def sigmoid(x):
    return 1/(1 + numpy.exp(-x))

def NN(m1, m2, w1, w2, b):
    z = m1 * w1 + m2 * w2 + b
    return sigmoid(z)

In [26]:
w1 = numpy.random.randn()
w2 = numpy.random.randn()
b = numpy.random.randn()

In [27]:
NN(3, 1.5, w1, w2, b)

-5.141035278740404

In [108]:
phrases = ['看起來像','我猜是','我想是','看起來像是','猜測....']
data = [[3, 1.5, 1],[2,1,0],[4,1.5,1],[3,1,0],[3.5,5,1],[2,0.5,0]]

In [109]:
rand_data = data[numpy.random.randint(len(data))]

In [110]:
m1 = rand_data[0]
m2 = rand_data[1]

In [111]:
prediction = NN(m1, m2, w1, w2, b)
prediction_text = ['藍色','紅色'][int(numpy.round(prediction))]
content = numpy.random.choice(phrases) + "" + prediction_text
out = ('這個' + content + "==真的是" + ["藍色","紅色"][rand_data[2]])
out

'這個猜測....藍色==真的是藍色'

In [180]:
import numpy as np

In [181]:
X = np.array([[1,0,1,0],[1,0,1,1],[0,1,0,1]])
y = np.array([[1],[1],[0]])

In [221]:
epoch = 5000
lr = 0.05
inputlayer_neurons = X.shape[1]
hiddenlayer_neurons = 1
output_neurons = 1

In [222]:
wh = np.random.uniform(size=(inputlayer_neurons, hiddenlayer_neurons))
bh = np.random.uniform(size=(1, hiddenlayer_neurons))
wout = np.random.uniform(size=(hiddenlayer_neurons, output_neurons))
bout = np.random.uniform(size=(1, output_neurons))

In [223]:
for i in range(epoch):
    #Forward Propogation
    hidden_layer_input1 = np.dot(X,wh)
    hidden_layer_input = hidden_layer_input1 + bh
    hiddenlayer_activations = sigmoid(hidden_layer_input)
    output_layer_input1 = np.dot(hiddenlayer_activations, wout)
    output_layer_input = output_layer_input1 + bout
    output = sigmoid(output_layer_input)
    
    #Backpropagation
    E = y-output
    back_output_layer = sigmoid(output)
    back_hidden_layer = sigmoid(hiddenlayer_activations)
    d_output = E * back_output_layer
    Error_at_hidden_layer = d_output.dot(wout.T)
    d_hiddenlayer = Error_at_hidden_layer * back_hidden_layer
    wout += hiddenlayer_activations.T.dot(d_output) * lr
    bout += np.sum(d_output, axis=0, keepdims=True) * lr
    wh += X.T.dot(d_hiddenlayer) * lr
    bh += np.sum(d_hiddenlayer, axis=0, keepdims=True) * lr

print('實際值：\n', y, '\n')
print('預測值：\n', output, '\n')

實際值：
 [[1]
 [1]
 [0]] 

預測值：
 [[0.98546267]
 [0.98546267]
 [0.06181176]] 



In [224]:
import torch

In [225]:
t = torch.zeros(2,3)

In [227]:
t = torch.rand(2, 3)

In [232]:
t

tensor([[ 0.7320,  0.5888,  0.0995],
        [ 0.7869,  0.5039,  0.1673]])

In [233]:
y

tensor([[ 0.2823,  0.8427,  0.2833],
        [ 0.8869,  0.3560,  0.9930]])

In [230]:
y = torch.rand(2,3)
print(t + y)

tensor([[ 1.0143,  1.4315,  0.3828],
        [ 1.6738,  0.8599,  1.1603]])


In [234]:
t.add(y)

tensor([[ 1.0143,  1.4315,  0.3828],
        [ 1.6738,  0.8599,  1.1603]])

In [239]:
t = torch.Tensor([[1,2,3],[4,5,6]])
t

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.]])

In [241]:
t.t()

tensor([[ 1.,  4.],
        [ 2.,  5.],
        [ 3.,  6.]])

In [242]:
t = torch.Tensor([[1,2],[3,4]])

In [245]:
t[:,-1]

tensor([ 2.,  4.])

In [247]:
if torch.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    x + y

In [248]:
a = torch.FloatTensor(2,3)
a

tensor(1.00000e-19 *
       [[ 0.0000,  0.0000,  0.0000],
        [ 1.0842,  0.0000,  0.0000]])

In [249]:
a.numpy()

array([[0.0000000e+00, 0.0000000e+00, 2.6560485e-29],
       [1.0842022e-19, 2.8025969e-45, 0.0000000e+00]], dtype=float32)

In [252]:
a = np.ones(5)
torch.from_numpy(a)

tensor([ 1.,  1.,  1.,  1.,  1.], dtype=torch.float64)

In [253]:
import torch
from torch.autograd import Variable
t = torch.ones(2,3)
v = Variable(t)
v.data

tensor([[ 1.,  1.,  1.],
        [ 1.,  1.,  1.]])

In [255]:
v = Variable(t, requires_grad = True)

In [257]:
x = Variable(torch.FloatTensor([2]),requires_grad=True)

In [258]:
y = x**2 + 4*x

In [259]:
y

tensor([ 12.])

In [260]:
y.backward()

In [262]:
x.grad

tensor([ 8.])